version: "3.7"

services:
  hackercv:
    build: .
    container_name: hackercv
    ports:
      - 8080:8080
    #  mount everything, except for node_modules
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
